// Render the generated legal document as a PDF and store in 'legal-docs' bucket.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";
import { jsPDF } from "https://esm.sh/jspdf@2.5.2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

function stripMd(s: string) {
  return s
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/\*\*(.+?)\*\*/g, "$1")
    .replace(/\*(.+?)\*/g, "$1")
    .replace(/`([^`]+)`/g, "$1");
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    const { documentId } = await req.json();
    if (!documentId) throw new Error("documentId required");

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const { data: doc, error } = await supabase
      .from("generated_documents").select("*").eq("id", documentId).single();
    if (error || !doc) throw new Error("Document not found");

    const pdf = new jsPDF({ unit: "pt", format: "a4" });
    const pageW = pdf.internal.pageSize.getWidth();
    const pageH = pdf.internal.pageSize.getHeight();
    const margin = 56;
    const maxW = pageW - margin * 2;
    let y = margin;

    // Header band
    pdf.setFillColor(22, 122, 65);
    pdf.rect(0, 0, pageW, 70, "F");
    pdf.setTextColor(255, 255, 255);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(20);
    pdf.text("NyayAI", margin, 32);
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");
    pdf.text("AI-assisted legal aid for India", margin, 50);
    pdf.text(new Date().toLocaleDateString("en-IN"), pageW - margin, 32, { align: "right" });

    y = 100;
    pdf.setTextColor(20, 30, 24);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(16);
    const titleLines = pdf.splitTextToSize(doc.title, maxW);
    pdf.text(titleLines, margin, y);
    y += titleLines.length * 20 + 10;

    if (doc.recipient) {
      pdf.setFontSize(11);
      pdf.setFont("helvetica", "italic");
      pdf.setTextColor(80, 90, 84);
      const rec = pdf.splitTextToSize(`To: ${doc.recipient}`, maxW);
      pdf.text(rec, margin, y);
      y += rec.length * 14 + 14;
    }

    pdf.setDrawColor(22, 122, 65);
    pdf.setLineWidth(1);
    pdf.line(margin, y, pageW - margin, y);
    y += 18;

    // Body
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(11);
    pdf.setTextColor(28, 36, 32);
    const bodyText = stripMd(doc.body_markdown);
    const paragraphs = bodyText.split(/\n\n+/);
    for (const p of paragraphs) {
      const lines = pdf.splitTextToSize(p.trim(), maxW);
      for (const line of lines) {
        if (y > pageH - 80) { pdf.addPage(); y = margin; }
        pdf.text(line, margin, y);
        y += 16;
      }
      y += 8;
    }

    // Footer
    const total = pdf.getNumberOfPages();
    for (let i = 1; i <= total; i++) {
      pdf.setPage(i);
      pdf.setFontSize(9);
      pdf.setTextColor(120, 130, 124);
      pdf.text(
        "Generated by NyayAI · Free legal aid · Verify with a NALSA legal services clinic before filing.",
        pageW / 2, pageH - 30, { align: "center" }
      );
      pdf.text(`Page ${i} of ${total}`, pageW - margin, pageH - 30, { align: "right" });
    }

    const pdfBytes = pdf.output("arraybuffer");
    const path = `${doc.case_id}/${documentId}.pdf`;
    const { error: upErr } = await supabase.storage.from("legal-docs").upload(path, pdfBytes, {
      contentType: "application/pdf", upsert: true,
    });
    if (upErr) throw upErr;

    const { data: pub } = supabase.storage.from("legal-docs").getPublicUrl(path);
    await supabase.from("generated_documents").update({ pdf_path: path }).eq("id", documentId);

    return new Response(JSON.stringify({ url: pub.publicUrl, path }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("generate-pdf error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown" }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
